# Generated by Django 4.0.5 on 2023-01-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_poo', '0002_addp_delete_addpatient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('ville', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=6)),
                ('adresse', models.TextField(max_length=50)),
                ('cin', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='AddP',
        ),
    ]
