# Generated by Django 4.0.5 on 2023-01-22 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet_poo', '0003_addpatient_delete_addp'),
    ]

    operations = [
    ]
