# Generated by Django 4.0.5 on 2023-01-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_poo', '0005_addpatient_date_addpatient_date_visite'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatient',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
