# Generated by Django 4.0.5 on 2023-01-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_poo', '0006_addpatient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatient',
            name='tuberculosis',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
